config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  resources :friends
  root "home#index"
  get "home/about"
=======
  resources :notes, except: [:index]
  devise_for :users

  root 'home#index'

>>>>>>> a0134d6 (Initial commit for AuraNotes project)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes, dependent: :destroy
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_path, status: :see_other, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.expect(friend: [ :first_name, :last_name, :email, :phone, :twiter ])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
<<<<<<< HEAD
  def index
    @name = "ali"
  end

  def about

  end
=======
    def index
        if user_signed_in?
            @notes = current_user.notes.all
        end
    end
>>>>>>> a0134d6 (Initial commit for AuraNotes project)
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = current_user.notes.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = current_user.notes.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy!

    respond_to do |format|
      format.html { redirect_to notes_path, status: :see_other, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.expect(note: [ :title, :description, :color, :user_id ])
    end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>
  <br>
  <div  class="field form-group">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
  </div>
  <br>
  <div class="field form-group">
    <%= form.text_field :twiter, class:"form-control", placeholder:"Twiter" %>
  </div>
<br>
  <div class="action">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twiter:</strong>
    <%= friend.twiter %>
  </p>

</div>

app/views/friends/edit.html.erb
<% content_for :title, "Editing friend" %>

<h1>Editing friend</h1>

<br>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-secondary" %> 
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
</div>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>

<% content_for :title, "Friends" %>


<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twiter</th>
      <th colspan = "3"></th>
    </tr>
  </thead>


<tbody>

  <% @friends.each do |friend| %>
    <tr>
    <td><%= friend.first_name %></td>
    <td><%= friend.last_name %></td>
    <td><%= friend.email %></td>
    <td><%= friend.phone %></td>
    <td><%= friend.twiter %></td>
    <td><%= link_to "Show", friend %></td>
    <td><%= link_to "Edit", edit_friend_path(friend) %></td>
    <td><%= link_to "Destroy", friend, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</tbody>
</table>
<br>

<%= link_to "New friend", new_friend_path, class:"btn btn-secondary" %>

app/views/friends/new.html.erb
<% content_for :title, "New friend" %>

<h1>Add New Friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
</div>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <h1 class="display-4">
    <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>
  <p class="lead">
    <%= @friend.email %>
  </p>
  <p class="lead">
    <%= @friend.phone %> 
  </p>
  <p class="lead">
    <%= @friend.twiter %>
  </p>
  <br>
  <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-secondary" %> 
  <%= link_to "Back", friends_path, class:"btn btn-secondary" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'Friends App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to 'About Us', home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Friends', friends_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Add Friend', new_friend_path, class:"nav-link" %>
        </li>
      </ul> 
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
</nav>

app/views/home/_landing.html.erb
<div class="container px-2">
  <div class="row gx-5">
    <div class="col p-3 d-flex flex-column justify-content-center align-items-start">
      <h1 class="display-1">Aura Notes</h1>
      <h3>Effortlessly organize your notes</h3>
      <%= link_to 'Get Started', new_user_registration_path, class:'mt-4 border border-black rounded py-2 px-4 btn btn-light hover:bg-gray-200 fw-semibold' %>
    </div>
    <div class="col p-3 mt-5">
      <%= image_tag 'aura_notes.svg' %>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<h1> This is about page. </h1>

app/views/home/index.html.erb
<<<<<<< HEAD
<h1>Hello <%=@name%> </h1>
=======
<% if user_signed_in? && @notes.count > 0 %>
  <div class="container py-5">

    <div id="notes" class="row g-4">
      <div class="col-12 col-sm-6 col-md-4 col-lg-3">
        <%= link_to new_note_path, class:"d-flex flex-column gap-2 text-center align-items-center justify-content-center border border-dashed b order-dark rounded p-4 text-decoration-none text-dark fw-semibold shadow-sm hover-shadow-lg" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-25 h-25">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
          </svg>
          Add Note
        <% end %>
      </div>

      <% @notes.each do |note| %>
        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
          <%= link_to note_path(note.id), class:"border border-dark rounded p-4 #{note.color} text-decoration-none text-dark fw-semibold d-block shadow-sm hover-shadow-lg" do %>
            <div>
              <p class="fs-4 text-truncate" style="max-width: 100%"><%= note.title.truncate(100) %></p>
              <p class="text-muted"><%= note.created_at.strftime("%d %b") %></p>
              <p class="mt-3 text-muted text-wrap" style="overflow: hidden; white-space: normal; text-overflow: ellipsis;"><%= note.description.truncate(100) %></p>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <%= render 'home/landing' %>
<% end %>
>>>>>>> a0134d6 (Initial commit for AuraNotes project)

app/views/layouts/_header.html.erb
<nav class="navbar bg-light shadow">
  <div class="container-fluid d-flex justify-content-around p-3">
    <%= link_to 'Aura Notes', root_path, class:'navbar-brand fw-bold fs-2' %>
      <div  class="d-flex gap-4">
        <% if user_signed_in? %>
          <%= link_to 'Log out', destroy_user_session_path, data: {"turbo-method": :delete}, class:'border border-black rounded py-2 px-4 btn btn-light hover:bg-gray-200 fw-semibold' %>
        <% else %>
          <%= link_to 'Log in', new_user_session_path, class:'border border-black rounded py-2 px-4 btn btn-light hover:bg-gray-200 fw-semibold' %>
        <% end %>
      </div>  
  </div>
</nav>

app/views/layouts/application.html.erb
<<<<<<< HEAD
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Friends App</title>

=======
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Auranotes" %></title>
>>>>>>> a0134d6 (Initial commit for AuraNotes project)
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<<<<<<< HEAD
    <%= render 'home/header' %>
    <div class="container">
    <br/>
    <%= yield :head %>
    <div/>
=======
    <%= yield :head %>
>>>>>>> a0134d6 (Initial commit for AuraNotes project)

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<<<<<<< HEAD

  </head>
  <body>
    <%= yield %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
=======
  </head>

  <body>
    <p class="text-center text-bg-success lh-8 fw-semibold"><%= notice %></p>
    <p class="text-center text-bg-danger lh-8 fw-semibold"><%= alert %></p>

    <% unless controller_name == 'registrations' || controller_name == 'sessions' || controller_name == 'passwords' %>
      <%= render 'layouts/header' %>
    <% end %>

    <%= yield %>
>>>>>>> a0134d6 (Initial commit for AuraNotes project)
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="mb-3">
    <%= form.label :title, style: "display: block", class:'form-label' %>
    <%= form.text_field :title, class:'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :description, style: "display: block", class:'form-label' %>
    <%= form.text_field :description, class:'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :color, style: "display: block", class:'form-label' %>
    <%= form.text_field :color, class:'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div id="<%= dom_id note %>" class="border border-dark rounded p-4 <%= note.color %> bg-light">
  <p class="fs-3 fw-light px-3">
    <strong>Title:</strong> <%= note.title %>
  </p>

  <div class="border-top border-dark w-100 py-3"></div>

  <p class="fs-5 px-3">
    <strong>Description:</strong> <%= note.description %>
  </p>

  <% if action_name != "show" %>
    <div class="mt-3">
      <%= link_to "Show this note", note, class: "btn btn-secondary me-2" %>
      <%= link_to "Edit this note", edit_note_path(note), class: "btn btn-secondary" %>
    </div>
  <% end %>
</div>

app/views/notes/edit.html.erb
<% content_for :title, "Editing note" %>

<div class="container mx-auto py-4">
  <h1 class="text-4xl mb-4">Editing note</h1>

  <%= render "form", note: @note %>

  <div class="mt-4">
    <%= link_to "Show this note", @note, class: "btn btn-primary me-2" %>
  </div>
</div>

app/views/notes/new.html.erb
<% content_for :title, "New note" %>

<div class="container mx-auto py-4">
  <h1 class="text-4xl mb-4">New note</h1>

    <%= render "form", note: @note %>
  
</div>

app/views/notes/show.html.erb
<p class="text-success"><%= notice %></p>

<div class="container mx-auto py-4">
  <div class="d-flex flex-column py-4">
    <%= render @note %>

    <div class="d-flex mt-4">
      <%= link_to "Edit this note", edit_note_path(@note), class: "btn btn-dark me-2" %>
    </div>

    <div class="mt-4">
      <%= button_to "Destroy this note", @note, method: :delete, class: "btn btn-danger" %>
    </div>
  </div>
</div>